### ISSUE TITLE
when distBaseUrl use http protocol，download node.js failed

### ISSUE THREAD

**Issue by humbinal** [node-gradle/gradle-node-plugin#201] opened 2021-10-21 10:38 UTC
I‘m use gradle version 7.2， and config distBaseUrl = “http://my-own-repo/node-dist”, got the error:
```
Using insecure prorocols with repositories, without explict opt-in, is unsupported.
```

how to support http protocol in this plugin.

in gradle config, it can use like this:
```
repositories {
  maven {
    allowInsecureProtocol = true
    url = 'http://my-own-repo/maven'
  }
}
```

**Comment by deepy** [comment] 2021-10-21 19:59
This is a duplicate of #163, there's also a workaround mentioned in there

**Closed by deepy** 2021-10-21 19:59 UTC
